# Generated by Django 4.1 on 2022-08-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_bids_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active_state',
            field=models.BooleanField(default=True),
        ),
    ]
